const AUTH_LOGIN = "AUTH_LOGIN";
const AUTH_INITIALIZED = "AUTH_INITIALIZED";
const AUTH_LOGOUT = "AUTH_LOGOUT";

const ACTIONS = {
  AUTH_LOGIN,
  AUTH_LOGOUT,
  AUTH_INITIALIZED,
};

export default ACTIONS;
