const AUTH_LOGIN = "AUTH_LOGIN";
const AUTH_INITIALIZES = "AUTH_INITIALIZED";
const AUTH_LOGOUT = "AUTH_LOGOUT";

const ACTIONS = {
  AUTH_LOGIN,
  AUTH_LOGOUT,
  AUTH_INITIALIZES,
};

export default ACTIONS;
