const AUTH_LOGIN = "AUTH_LOGIN";
const AUTH_INITIALIZED = "AUTH_INITIALIZED";
const AUTH_LOGOUT = "AUTH_LOGOUT";
const AUTH_ERROR = "AUTH_ERROR";

const ACTIONS = {
  AUTH_LOGIN,
  AUTH_LOGOUT,
  AUTH_INITIALIZED,
  AUTH_ERROR,
};

export default ACTIONS;
